Further fixes
Further fixes. JSExternalStringSizeofCallback does not exist in current js engine and GeckoProfiler is renaming of SPSProfiler.

GCRuntime.h(102): error C2614: 'js::gc::BackgroundDecommitTask': illegal member initialization: 'GCParallelTask' is not a base or member

AtomicsObject.cpp(772): error C2668: 'js::ToNumber': ambiguous call to overloaded function

These issues remain.